### ISSUE TITLE
Lock specification

### ISSUE THREAD

**Issue by vonj** [runekaagaard/snowscript#13]
IMHO you should focus on _locking_ the language spec. as soon as possible. 

Why?  Snowscript needs some early adopters. But no one wants to go first and write a bunch of code only to have it break on some new release of snowscript.

(Also it would be fabulous if somehow, magically, snowscript could be bootstrapped kind of like Coffescript can be, but that is something else.)

**Comment by vendethiel** [comment]
Agreed

**Comment by runekaagaard** [comment]
Snowscript needs first of all developers. Much work has gone in to it, but there is still a looooong way to go. Since I've started doing snowscript, we've almost completely migrated to Python at work, so the pain points of PHP is quite far behind me now.

I don't have any monetary incentives doing Snowscript, so I only work on it when I find thats the most fun way to spend my time. At the moment, the most fun is other things, but who knows? It would be GREAT to see some one else pick up the gauntlet too.

Thanks for opening this issue, and looking forward hearing your replies.

**Comment by vonj** [comment]
We are also making a transition away from PHP...

**Comment by vendethiel** [comment]
I'm not a Python fan but I certainly feel your joy!
