### ISSUE TITLE
Reason not to unset variable after loop (historical behavior)

### ISSUE THREAD

**Issue by babakness** [runekaagaard/snowscript#4]
Hello, great work I'm really looking forward to this!

Looking at your 99 bottles example i noticed the automatic "unset($i);" I believe it is prudent not to do this.  Example (python)

``` python
# Professor wants first score after his expectation to be the cut-off.
for student,grade in test_results:
  if grade < expected: break
print "Test cut-off score: %s" % grade 
# Perhaps lots more code, prefer to handle outside of if-statement in loop.
```

Otherwise I would declare a variable "cut off" before the loop and set it within the loop just before break. Just extra lines of code but I can appreciate the notion/philosophy that loops should not themselves introduce variables into our scope; although historically they do (C, Javascript, PHP, Python, etc.).

``` python
for i in [1,2,3,4]:
  print i

#1
#2
#3
#4

print i

#4
```

**Comment by runekaagaard** [comment]
Hey

Thanks a lot for taking an interest, and this feedback! While there are some use cases where it would be convenient to have the last key and value available outside the loop, most of the time it just messes up the scope, IMO. Especially when considering the pitfalls to using the value by reference. https://bugs.php.net/bug.php?id=29992 and countless others.

Yes, looking forward to it as well :) Theres still tons of work to be done, so if you want to try your luck with compilers and lexers, any help would be awesome!!!!

Cheers

**Comment by babakness** [comment]
Those are some good examples! I agree with you philosophically that it is good coding practice not to have variables running around. Yet there are other reasons I'm stumped on, here are two of them

# Nested loops

``` python
for key1,arr in mixed_multi.items():
   for key2,obj in arr:
      if type(obj) == type(''): arr[key2] = [obj]

   ##  Would expect arr to exist!  ##
   mixed_multi[key1] = OrderedDict(sorted(arr.items(), key=lambda t: t[0]))
```

# Staying out-of-the-way

The other thing is that people may want to convert PHP to Snowscript

http://js2coffee.org/

It would be difficult to correctly predict if the variable in a PHP loop should be unset upon loop completion or not (and not break the logic in the original code). I feel that Javascript/Coffee producing each other on the fly is due to a scalable and out-of-the-way philosophy. My thinking is that if PHP changed the way loops worked the entire community would adapted in time--a language that compiles down to PHP would produce the behavior expected depending on any fork or version of PHP used by users during their transition.

Perhaps some way to syntactically signal to the compiler not to unset? It may add some weight but it would only be experienced if someone wanted to preserve the variable after its use. A future PHP to Snowscript would have to do this (or else setup a variable swap in the resulting Snowscript each time, adding lots of code).

Anyway, I really like some of the syntax choices here, the '<- function(4)->function2->function3' syntax is brilliant! I've learned a lot looking over your code. I also found a nice article you may already know about regarding List Comprehensions:

http://stackoverflow.com/questions/1266911/does-php-have-an-equivalent-to-pythons-list-comprehension-syntax

**Comment by runekaagaard** [comment]
# Nested loops

But `arr` will exist. It will first be unset after the first loop

```
# Snowscript
for x in xs
    for y in ys
        pass

// PHP
foreach ($xs as $x) {
    foreach ($ys as $y) {

    }
    unset($y);
}
unset($x);
```

# Staying out-of-the-way

Its definitely a balance, to at the same time, try to improve the language
while not drifting too far apart from it, so it would make no sense to use it
with existing PHP code. It seems a lot harder than coffeescript because
javascript is way smaller, neater and (yes shocking) better designed than PHP.  

My first iteration of specs for Snowscript was closer to PHP, but I felt 
offered too few improvements (http://code.google.com/p/php-snow/).

Macros will be a part of Snowscript eventually, so something like:

```
@for x in xs
   x->do()
```

could be made. But it's so far away that I've not even started thinking about
it yet :)

Thanks for the kind words, I've learned a lot too perusing many a weird language
to get inspiration from. There is definitely benefits from obsessing over 
languages, syntax, etc.

List comprenhensions are already in the docs, was there something specific you
wanted me to see in the link?
