### ISSUE TITLE
Strings can be concatenated using the "%" operator.

### ISSUE THREAD

**Issue by xeoncross** [runekaagaard/snowscript#5]
This is not a good idea. You never want to replace commonly used characters with difficult keyboard combos. A period is simple (a single key) and located in a well known and used place making it easy for the mind to locate.

Replacing a period with a SHIFT+5 key-combo is a bad move for something as common as string concatenation.

In fact, periods should be used for as many things as possible given their appealing, and common nature in written prose.

```
namespace.class.property = 'Foo' . 'Bar';
```

**Comment by jwoertink** [comment]
Hmm.. I do agree that % is a weird character for string concatenation, but if the idea of snowscript is to use PHP without all the ugliness, then I'd say take what Python, Ruby, Go, Scala, JavaScript, CoffeeScript all do, and use a + character. Lua uses two dots .. which is a little strange, but I guess that would be sort of a compromise. Snowscript claims to take the best parts from these languages, so might as well use things they do.

Then again, since @runekaagaard is making this, I guess rock out what _you_ like! :)

**Comment by xeoncross** [comment]
I agree that the `+` is more logical - it's just harder to type than `.` on a QWERTY keyboard.

Which brings me to the real problem - keyboards aren't built for programmers and most people can't make the switch because of multiple shared machines or what not.

I assume that @runekaagaard chose the `%` because it made writing the lexer easier since that isn't a common character, which seems like a bad reason to choose it.

**Comment by runekaagaard** [comment]
@Xeoncross Why open another issue?, you voiced the same concern at https://github.com/runekaagaard/snowscript/issues/1

I too would prefer to use `+` to concat strings. But as Snowscript is dynamically typed, how would you know if

```
func1() + func2()
```

Should compile to: (remember we are compiling to PHP)

```
func1() . func2();
```

or

```
func1() + func2();
```

Here's two examples of idiomatic Snow code dealing with joining strings:

``` python
"""Please {join} this and {this()}""""
```

and

``` python
fn get_text(things)
    <- ["<li>{x.title}: {x.description}</li>" for x in things]->implode()
```

**Comment by xeoncross** [comment]
I'm sorry @runekaagaard, I honestly had no idea I already mentioned this. Thanks for taking the time to explain the issue more.

However, why are you trying change both `+` and `.` from their native usage in PHP? Why can't they be explicit?

```
$string = func1() . func2();
$number = func1() + func2();
```

I guess my question is, why did you opt for the `%` character to begin with? Why can't the `.` be used for both classes and concatenation?

**Comment by runekaagaard** [comment]
@Xeoncross `.` Can't be used for both classes and concatenation because it can't in PHP. We don't know the return types of `func1()` and `func2()` so there is no way of knowing if we should compile to a `+` or a `.` in between.

So the design choice in PHP, that summing numbers and concatenating strings should have different operators, makes it impossible to use a single operator for both operations in Snowscript. If you don't believe me, dive into the code and try for yourself :)

And why `%`? Well my first priority was to use `.` for object access. With `+` unavailable too it seemed like the least bad option.

**Comment by 00dani** [comment]
To revive an incredibly old and closed issue, you can _absolutely_ use `.` for both method-sends and string concatenation, like so:

``` snowscript
result = object.method()
result = string . otherstring
```

Of course, this might be inconvenient for long chains of string concatenation, and the seeming ambiguity between the two syntaxes is perhaps smelly.

`+` could be made an addition/concatenation operator without much difficulty, really:

``` snowscript
result = func1() + func2()
```

``` php
$result = snow_plus(func1(), func2());
```

This'd also be a way to permit general operator overloading! Of course, there's a performance hit in dispatching through a `snow_` function at runtime, so that's got to be considered too.

**Comment by vendethiel** [comment]
I never seen `%` for script concatenation.
- is runtime, . is ambigous, so they probably don't fit ... You can use `~`, à la Perl 6.

**Comment by dhaarbrink** [comment]
Isn't it possible to have implicit concatenation?

result = func1() func2()

**Comment by 00dani** [comment]
@Nami-Doc Snowscript already defers common operations to runtime `snow_` functions. In particular, `<` compiles to `snow_lt` and likewise for other comparison operators, to ensure strongly-typed comparison. Doing the same to `+` to allow strongly-typed addition/concatenation seems entirely in line with the language philosophy.

**Comment by vendethiel** [comment]
I like the idea of having one operator for one kind of data, though. It's not the same as `<` : this uses runtime functions to exactly have one operator for one kind of data
